### PR TITLE
Target net45

### PR DESCRIPTION
**Pull request by hanabi1224**
@iwillspeak  Add net45 target as well as some CI badges

### CODE REVIEW

**Comment by hanabi1224** [comment]
@iwillspeak  I need to reference this package from a lib that is below net47,  I don't see why it cannot be targeted to net45, plz let me know your concerns

**Comment by hanabi1224** [comment]
@iwillspeak  kindly ping

**Comment by iwillspeak** [comment]
Sorry, looks like this got buried for some reason. I’m up for taggetting net45. Might be better to add a compatible net standard target though? That would help people targetting older versions of other frameworks too. I’m happy to merge this though. Will look over it and merge next time i have a laptop.

**Comment by iwillspeak** [comment]
After having thought about it we cant' get away with just Netstandard for the older .NET Framework support. I'm pulling together a new set of builds for the batteries right now. I'll update this PR and merge when I have those.

**Comment by iwillspeak** [comment]
@hanabi1224 Could you separate out the net45 changes from the code coverage changes and squash  down into a single commit please?

**Comment by iwillspeak** [comment]
I've squashed this down and filtered out the code coverage stuff. I'd be interested in accepting that as a separate PR, just wanted to make this one simpler right now.

**Comment by hanabi1224** [comment]
@iwillspeak  ty so much!

**Pull request merged**
